n = input('Digite qualquer coisa: ')
print(type(n))
print('É Alfanumerico? ',n.isalnum())
print('É uma Alfabetico? ',n.isalpha())
print('Possui codigo? ',n.isascii())
print('é um decimal? ',n.isdecimal())
print('Tem algum digito? ',n.isdigit())
print('Possui uma palavra reservada? ',n.isidentifier())
print('Está em minusculo? ',n.islower())
print('E um numero?? ',n.isnumeric())
print('E imprimivel? ',n.isprintable())
print('So tem espaço? ',n.isspace())
print('Esta capitalizada? ',n.istitle())
print('Esta em maiuscula? ',n.isupper())
